### ISSUE TITLE
bin/config fails on clean box

### ISSUE THREAD

**Issue by WillEngler** [Pitt-CSC/handy#18]
After following the instructions in the README, @wyb1 and I were unable to run the setup script. If we find a solution, we'll update the documentation or the script accordingly.

Output:

```
vagrant@precise64:handy$ bin/setup -v
Setting up Handy for development:
* Clearing logs and temporary files
* Installing dependencies
  - Ruby
    rbenv: no such command `install'
```

**Comment by WillEngler** [comment]
Another issue: a JS environment is assumed.

```
vagrant@precise64:handy$ rake db:drop db:create db:schema:load --trace
rake aborted!
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://
github.com/sstephenson/execjs for a list of available runtimes.
```

**Comment by WillEngler** [comment]
Update: figured out the system dependencies. Once I finish configuring my VM, I'm aiming to make a Vagrant base box for the army of first-time contributors I'm building. Failing that, I'll have a nice how-to document or a script.

**Comment by georgeclaghorn** [comment]
Awesome, Will!

**Comment by WillEngler** [comment]
Proposed guide in Pull Request #20.

**Comment by georgeclaghorn** [comment]
Closing this now that we have @WillEngler's Vagrant-based development environment.
